%% @doc Harness for the brazilian-utils API contract suite.
%%
%% Runs every case of the language-agnostic conformance suite vendored in
%% `api-contract/' (see `api-contract/README.md'), one EUnit test per case,
%% named by the case id. The suite is never edited here: expectations change
%% in brazilian-utils/docs, behaviour changes in this lib.
%%
%% Adding a function to the lib = implementing it + one line in
%% {@link registry/0}. Cases the lib does not pass yet are listed in
%% `api-contract/skip.json' (regenerated by the docs refresh).
%%
%% EUnit has no native "skipped" status, so a skipped case (or function) is
%% an empty test group titled `"SKIPPED <id>: <reason>"': it shows up in
%% verbose output, runs nothing and is counted neither as passed nor failed.
%%
%% Environment:
%%   API_CONTRACT_NETWORK=1   also run functions marked `network: true'
%%   API_CONTRACT_NO_SKIP=1   ignore `skip.json' (to check it is up to date)
%%   API_CONTRACT_DIR=<path>  use this `api-contract/' directory
-module(brutils_api_contract_tests).

-include_lib("eunit/include/eunit.hrl").

%%--------------------------------------------------------------------
%% Registry: contract function id -> lib function
%%--------------------------------------------------------------------

%% One line per contract function this lib implements. The value is any
%% fun whose arity matches the case's `args' (JSON strings arrive as
%% binaries, `null' as `undefined', objects as maps with binary keys).
%% `{ok, V}' is unwrapped and `{error, _}' is the idiomatic "no result"
%% (it satisfies both `returns: null' and `throws'); results are compared
%% in JSON form (atoms as strings, tuples as arrays).
registry() ->
    [%% CEP
     {<<"cep.format">>, fun brutils:format_cep/1},
     {<<"cep.generate">>, fun brutils:generate_cep/0},
     {<<"cep.isValid">>, fun brutils:is_valid_cep/1},
     %% CNH
     {<<"cnh.isValid">>, fun brutils:is_valid_cnh/1},
     %% CNPJ
     {<<"cnpj.format">>, fun brutils:format_cnpj/1},
     {<<"cnpj.generate">>, fun brutils:generate_cnpj/0},
     {<<"cnpj.isValid">>, fun brutils:is_valid_cnpj/1},
     %% CPF
     {<<"cpf.format">>, fun brutils:format_cpf/1},
     {<<"cpf.generate">>, fun brutils:generate_cpf/0},
     {<<"cpf.isValid">>, fun brutils:is_valid_cpf/1},
     %% License plate
     {<<"licensePlate.convertToMercosul">>,
      fun brutils:convert_license_plate_to_mercosul/1},
     {<<"licensePlate.format">>, fun brutils:format_license_plate/1},
     {<<"licensePlate.generate">>, fun brutils:generate_license_plate/0},
     {<<"licensePlate.getFormat">>, fun brutils:get_format_license_plate/1},
     {<<"licensePlate.isValid">>, fun brutils:is_valid_license_plate/1},
     %% Passport
     {<<"passport.format">>, fun brutils:format_passport/1},
     {<<"passport.generate">>, fun brutils:generate_passport/0},
     {<<"passport.isValid">>, fun brutils:is_valid_passport/1},
     %% Phone
     {<<"phone.format">>, fun brutils:format_phone/1},
     {<<"phone.generate">>, fun brutils:generate_phone/0},
     {<<"phone.isValid">>, fun brutils:is_valid_phone/1},
     {<<"phone.removeInternationalDialingCode">>,
      fun brutils:remove_international_dialing_code/1},
     %% PIS
     {<<"pis.format">>, fun brutils:format_pis/1},
     {<<"pis.generate">>, fun brutils:generate_pis/0},
     {<<"pis.isValid">>, fun brutils:is_valid_pis/1},
     %% RENAVAM
     {<<"renavam.isValid">>, fun brutils:is_valid_renavam/1},
     %% Voter ID
     {<<"voterId.format">>, fun brutils:format_voter_id/1},
     {<<"voterId.generate">>, fun brutils:generate_voter_id/0},
     {<<"voterId.isValid">>, fun brutils:is_valid_voter_id/1}].

%%--------------------------------------------------------------------
%% Tests
%%--------------------------------------------------------------------

%% One test per case of every domain file, grouped by contract function.
contract_test_() ->
    Dir = contract_dir(),
    Registry = maps:from_list(registry()),
    Skips = skips(Dir),
    [function_tests(Fn, Registry, Skips) || Fn <- suite_functions(Dir)].

%% A registry entry the suite does not know is a typo or a renamed
%% contract function.
registry_ids_are_in_the_suite_test() ->
    Known = [maps:get(<<"id">>, Fn) || Fn <- suite_functions(contract_dir())],
    ?assertEqual([], [Id || {Id, _} <- registry(),
                            not lists:member(Id, Known)]).

%% The comparison function judges every pair of `cases/equality.json' like
%% every other lib's harness does.
equality_self_test_() ->
    File = filename:join([contract_dir(), "cases", "equality.json"]),
    Pairs = read_json(File),
    [{title(["equality: ", maps:get(<<"why">>, P)]),
      ?_assertEqual(maps:get(<<"equal">>, P),
                    equal(json_form(maps:get(<<"expected">>, P)),
                          json_form(maps:get(<<"actual">>, P))))}
     || P <- Pairs].

function_tests(Fn, Registry, Skips) ->
    Id = maps:get(<<"id">>, Fn),
    Offline = maps:get(<<"network">>, Fn, false) =:= true
        andalso os:getenv("API_CONTRACT_NETWORK") =/= "1",
    case maps:find(Id, Registry) of
        error ->
            skipped(Id, <<"not implemented">>);
        {ok, _} when Offline ->
            skipped(Id, <<"network function (set API_CONTRACT_NETWORK=1)">>);
        {ok, Fun} ->
            {title(Id),
             [case_test(C, Fun, Registry, Skips)
              || C <- maps:get(<<"cases">>, Fn)]}
    end.

case_test(Case, Fun, Registry, Skips) ->
    Id = maps:get(<<"id">>, Case),
    Args = maps:get(<<"args">>, Case),
    Expect = expectation(maps:get(<<"expect">>, Case)),
    Target = case Expect of
                 {satisfies, T} -> maps:find(T, Registry);
                 _ -> none
             end,
    if
        is_map_key(Id, Skips) ->
            skipped(Id, maps:get(Id, Skips));
        Target =:= error ->
            skipped(Id, [element(2, Expect), <<" is not implemented">>]);
        not is_function(Fun, length(Args)) ->
            skipped(Id, io_lib:format("the lib function does not take ~b "
                                      "argument(s)", [length(Args)]));
        true ->
            Repeat = maps:get(<<"repeat">>, Case, 1),
            {title(Id),
             fun() ->
                     lists:foreach(
                       fun(_) -> check(Expect, call(Fun, Args), Target) end,
                       lists:seq(1, Repeat))
             end}
    end.

skipped(Id, Reason) ->
    {title(["SKIPPED ", Id, ": ", Reason]), []}.

%%--------------------------------------------------------------------
%% Expectations
%%--------------------------------------------------------------------

expectation(#{<<"returns">> := V}) -> {returns, V};
expectation(#{<<"throws">> := true}) -> throws;
expectation(#{<<"matches">> := Re}) -> {matches, Re};
expectation(#{<<"satisfies">> := Fn}) -> {satisfies, Fn}.

%% Outcome of a call: {ok, JsonValue} | {absent, Reason} | {raised, C, R}.
call(Fun, Args) ->
    try apply(Fun, [lib_arg(A) || A <- Args]) of
        {error, Reason} -> {absent, Reason};
        {ok, V} -> {ok, json_form(V)};
        V -> {ok, json_form(V)}
    catch
        Class:Reason -> {raised, Class, Reason}
    end.

check({returns, null}, {absent, _}, _) -> ok;
check({returns, Expected}, {ok, Actual}, _) ->
    equal(Expected, Actual) orelse fail(Expected, {ok, Actual});
check({returns, Expected}, Outcome, _) -> fail(Expected, Outcome);
check(throws, {ok, _} = Outcome, _) -> fail(an_error, Outcome);
check(throws, _, _) -> ok;
check({matches, Re}, {ok, Actual}, _) when is_binary(Actual) ->
    re:run(Actual, Re, [unicode]) =/= nomatch
        orelse fail({matches, Re}, {ok, Actual});
check({matches, Re}, Outcome, _) -> fail({matches, Re}, Outcome);
check({satisfies, Fn}, {ok, Actual}, {ok, Target}) ->
    call(Target, [Actual]) =:= {ok, true}
        orelse fail({satisfies, Fn}, {ok, Actual});
check({satisfies, Fn}, Outcome, _) -> fail({satisfies, Fn}, Outcome).

fail(Expected, Outcome) ->
    erlang:error({contract_mismatch, [{expected, Expected}, {got, Outcome}]}).

%%--------------------------------------------------------------------
%% Comparison (cases/index.json -> comparison)
%%--------------------------------------------------------------------

%% `Expected' and `Actual' are both in JSON form (see json_form/1).
equal(null, Actual) -> Actual =:= null;
equal(E, A) when is_number(E), is_number(A) ->
    abs(E - A) =< 1.0e-9 * max(1, abs(E));
equal(E, A) when is_list(E), is_list(A), length(E) =:= length(A) ->
    lists:all(fun({X, Y}) -> equal(X, Y) end, lists:zip(E, A));
equal(E, A) when is_map(E), is_map(A) ->
    NE = normalize_keys(E),
    NA = normalize_keys(A),
    lists:all(fun(K) -> equal(maps:get(K, NE, null), maps:get(K, NA, null)) end,
              lists:usort(maps:keys(NE) ++ maps:keys(NA)));
equal(E, A) -> E =:= A.

%% zipCode == zip_code == ZipCode: lowercase, keep only a-z and 0-9.
normalize_keys(Map) ->
    maps:from_list([{flat_key(K), V} || {K, V} <- maps:to_list(Map)]).

flat_key(K) ->
    re:replace(string:lowercase(K), "[^a-z0-9]", "",
               [global, unicode, {return, binary}]).

%% A lib value in JSON form: strings as binaries, atoms as strings,
%% null/undefined/nil as null, tuples as arrays, maps with binary keys.
json_form(V) when V =:= null; V =:= undefined; V =:= nil -> null;
json_form(V) when is_boolean(V); is_number(V); is_binary(V) -> V;
json_form(V) when is_atom(V) -> atom_to_binary(V, utf8);
json_form(V) when is_tuple(V) -> json_form(tuple_to_list(V));
json_form(V) when is_list(V) -> [json_form(X) || X <- V];
json_form(V) when is_map(V) ->
    maps:from_list([{json_key(K), json_form(X)} || {K, X} <- maps:to_list(V)]);
json_form(V) -> iolist_to_binary(io_lib:format("~0p", [V])).

json_key(K) when is_binary(K) -> K;
json_key(K) when is_atom(K) -> atom_to_binary(K, utf8);
json_key(K) -> iolist_to_binary(io_lib:format("~0p", [K])).

%% A JSON value as the lib receives it: null becomes `undefined'.
lib_arg(null) -> undefined;
lib_arg(L) when is_list(L) -> [lib_arg(X) || X <- L];
lib_arg(M) when is_map(M) -> maps:map(fun(_, V) -> lib_arg(V) end, M);
lib_arg(V) -> V.

%%--------------------------------------------------------------------
%% Suite files
%%--------------------------------------------------------------------

suite_functions(Dir) ->
    Pattern = filename:join([Dir, "cases", "*.json"]),
    Files = lists:sort(filelib:wildcard(Pattern)),
    lists:append([maps:get(<<"functions">>, read_json(F))
                  || F <- Files,
                     not lists:member(filename:basename(F),
                                      ["index.json", "equality.json"])]).

skips(Dir) ->
    case os:getenv("API_CONTRACT_NO_SKIP") of
        "1" -> #{};
        _ -> read_json(filename:join(Dir, "skip.json"))
    end.

%% `api-contract/' at the repo root, found from this module's source (as
%% recorded, absolute, by the compiler) and beam locations and from the
%% cwd, walking up (rebar3 runs tests from `_build/test/lib/brutils',
%% plain erl from anywhere).
contract_dir() ->
    case os:getenv("API_CONTRACT_DIR") of
        false ->
            Source = proplists:get_value(source, module_info(compile), ?FILE),
            Starts = [filename:dirname(Source),
                      filename:dirname(code:which(?MODULE)),
                      element(2, file:get_cwd())],
            case lists:search(fun is_contract_dir/1,
                              lists:append([ancestors(S) || S <- Starts,
                                                            is_list(S)])) of
                {value, Root} -> filename:join(Root, "api-contract");
                false -> erlang:error({api_contract_not_found, Starts})
            end;
        Dir ->
            Dir
    end.

is_contract_dir(Root) ->
    Index = filename:join([Root, "api-contract", "cases", "index.json"]),
    filelib:is_regular(Index).

ancestors(Path) ->
    Abs = filename:absname(Path),
    case filename:dirname(Abs) of
        Abs -> [Abs];
        Parent -> [Abs | ancestors(Parent)]
    end.

title(Chars) -> unicode:characters_to_list(Chars).

%%--------------------------------------------------------------------
%% JSON
%%--------------------------------------------------------------------

%% OTP 27+ ships `json'; the lib supports OTP 25 and 26 too, which do not,
%% and adds no dependency for tests. On those releases a small decoder
%% (RFC 8259, same term shapes as `json:decode/1': binaries, maps with
%% binary keys, `null') reads the suite. Drop it once minimum_otp_vsn >= 27.
read_json(File) ->
    {ok, Bin} = file:read_file(File),
    _ = code:ensure_loaded(json),
    case erlang:function_exported(json, decode, 1) of
        true -> json:decode(Bin);
        false -> decode(Bin)
    end.

decode(Bin) ->
    {Value, Rest} = value(ws(Bin)),
    <<>> = ws(Rest),
    Value.

value(<<${, R/binary>>) -> object(ws(R), #{});
value(<<$[, R/binary>>) -> array(ws(R), []);
value(<<$", R/binary>>) -> string(R, []);
value(<<"true", R/binary>>) -> {true, R};
value(<<"false", R/binary>>) -> {false, R};
value(<<"null", R/binary>>) -> {null, R};
value(Bin) -> number(Bin).

object(<<$}, R/binary>>, Acc) when Acc =:= #{} -> {Acc, R};
object(<<$", R0/binary>>, Acc) ->
    {Key, R1} = string(R0, []),
    <<$:, R2/binary>> = ws(R1),
    {Value, R3} = value(ws(R2)),
    case ws(R3) of
        <<$,, R4/binary>> -> object(ws(R4), Acc#{Key => Value});
        <<$}, R4/binary>> -> {Acc#{Key => Value}, R4}
    end.

array(<<$], R/binary>>, []) -> {[], R};
array(Bin, Acc) ->
    {Value, R0} = value(Bin),
    case ws(R0) of
        <<$,, R1/binary>> -> array(ws(R1), [Value | Acc]);
        <<$], R1/binary>> -> {lists:reverse([Value | Acc]), R1}
    end.

string(<<$", R/binary>>, Acc) ->
    {unicode:characters_to_binary(lists:reverse(Acc)), R};
string(<<$\\, $u, Hex:4/binary, R0/binary>>, Acc) ->
    case {binary_to_integer(Hex, 16), R0} of
        {Hi, <<$\\, $u, LoHex:4/binary, R1/binary>>}
          when Hi >= 16#D800, Hi =< 16#DBFF ->   % surrogate pair
            Lo = binary_to_integer(LoHex, 16),
            C = 16#10000 + ((Hi - 16#D800) bsl 10) + (Lo - 16#DC00),
            string(R1, [C | Acc]);
        {C, _} ->
            string(R0, [C | Acc])
    end;
string(<<$\\, C, R/binary>>, Acc) ->
    string(R, [unescape(C) | Acc]);
string(<<C/utf8, R/binary>>, Acc) ->
    string(R, [C | Acc]).

unescape($") -> $";
unescape($\\) -> $\\;
unescape($/) -> $/;
unescape($b) -> $\b;
unescape($f) -> $\f;
unescape($n) -> $\n;
unescape($r) -> $\r;
unescape($t) -> $\t.

number(Bin) ->
    Re = "^-?(0|[1-9][0-9]*)(\\.[0-9]+)?([eE][-+]?[0-9]+)?",
    {match, [Text]} = re:run(Bin, Re, [{capture, first, binary}]),
    <<_:(byte_size(Text))/binary, R/binary>> = Bin,
    {number_value(Text), R}.

number_value(Text) ->
    try binary_to_integer(Text)
    catch error:badarg ->
            %% Erlang floats need a fraction: 1e5 -> 1.0e5.
            case binary:match(Text, <<".">>) of
                nomatch ->
                    [M, E] = re:split(Text, "[eE]", [{return, binary}]),
                    binary_to_float(<<M/binary, ".0e", E/binary>>);
                _ ->
                    binary_to_float(Text)
            end
    end.

ws(<<C, R/binary>>) when C =:= $\s; C =:= $\t; C =:= $\n; C =:= $\r -> ws(R);
ws(Bin) -> Bin.
